import { Albert_Sans } from "next/font/google";
import "./globals.css";
import "./css/main.css";
import "./css/responsive.css";
import "./css/smooth-scroll.css";
import MusicComp from "./Home/musicComp";
import SmoothScrolliing from "./components/smoothScrolling";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-albert-sans",
  display: "swap",
});

export const metadata = {
  title: "Innersmith",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${albertSans.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <MusicComp src="/musicbg.mp3" autoPlay={false} />
        <SmoothScrolliing>{children}</SmoothScrolliing>
      </body>
    </html>
  );
}
