import { Albert_Sans } from "next/font/google";
import "./globals.css";
import "./css/main.css";
import "./css/responsive.css";
import MusicComp from "./Home/musicComp";
import SmoothScrolliing from "./components/smoothScrolling";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add weights you need
  variable: "--font-albert-sans", // optional, for CSS variables
  display: "swap",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Innersmith",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${albertSans.variable}  antialiased`}>
        {/* <audio
          autoPlay
          loop
          controls={false}
          style={{ display: "none" }}
          src="/musicbg.mp3"
        /> */}
        <MusicComp src="/musicbg.mp3" autoPlay={false} />
        <SmoothScrolliing>
        {children}
        </SmoothScrolliing>
      </body>
    </html>
  );
}
